import type { Store } from "@/types/models";

export const MOCK_STORES: Store[] = [
  {
    id: "mock-gangnam",
    name: "만월경 강남점",
    type: "무인",
    address: "서울 강남구 강남대로 396",
    latitude: 37.497952,
    longitude: 127.027619,
    phone: "02-555-1201",
    parking: "불가",
    toilet: "있음",
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "mock-samsung",
    name: "데이롱 삼성점",
    type: "무인",
    address: "서울 강남구 테헤란로 508",
    latitude: 37.508812,
    longitude: 127.063142,
    phone: "02-555-1202",
    parking: "가능",
    toilet: "있음",
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "mock-hongdae",
    name: "탐앤탐스 홍대점",
    type: "일반",
    address: "서울 마포구 양화로 160",
    latitude: 37.555946,
    longitude: 126.923011,
    phone: "02-555-1203",
    parking: "불가",
    toilet: "있음",
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "mock-sillim",
    name: "커피에반하다 신림점",
    type: "무인",
    address: "서울 관악구 신림로 330",
    latitude: 37.4842,
    longitude: 126.9296,
    phone: "02-555-1204",
    parking: "불가",
    toilet: "없음",
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "mock-jamsil",
    name: "스타벅스 잠실점",
    type: "일반",
    address: "서울 송파구 올림픽로 240",
    latitude: 37.5133,
    longitude: 127.1001,
    phone: "02-555-1205",
    parking: "가능",
    toilet: "있음",
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
];
